import React from 'react';
import { AlignCenter, AlignLeft, AlignRight, Bold, ChevronDown, Italic, List, ListOrdered, Minus, Plus, Underline } from 'lucide-react';
import { CANVAS_FONTS } from '../core/index.ts';
import type { CanvasShape } from './InfiniteCanvas';
import { effectiveText } from './canvasGeometry';
import { CANVAS_FONT_KEYS, canvasFontFromValue, fontSizeForShape, textAlignForShape } from './canvasText';
import { CANVAS_UI_COLORS } from './theme';
interface Props { s: CanvasShape; isDarkMode: boolean; editing: boolean; installedFontFamilies: readonly string[]; patchSelected: (patch: Partial<CanvasShape>) => void; applyFormat: (command: 'bold'|'italic'|'underline') => void; applyList: (kind:'bullet'|'dash'|'number') => void; applyCustomFontFamily:(value:string)=>void; }
export function CanvasInspectorText({s,isDarkMode,editing,installedFontFamilies,patchSelected,applyFormat,applyList,applyCustomFontFamily}:Props) {
const size=fontSizeForShape(s);
const btn=isDarkMode?'text-slate-200 hover:bg-slate-800':'text-slate-700 hover:bg-slate-100';
return <>      <div className="flex flex-wrap items-center gap-2 pointer-events-none">
        <span className="pointer-events-none px-1 text-[10px] font-semibold tracking-wide opacity-60">텍스트</span>
        <label title="글씨 색" className="pointer-events-auto w-8 h-8 rounded-lg border relative overflow-hidden cursor-pointer flex items-center justify-center text-[11px] font-bold shadow-sm" style={{ background: effectiveText(s), color: CANVAS_UI_COLORS.white, mixBlendMode: 'normal' }}><span aria-hidden="true">A</span><input data-canvas-control="text-color" type="color" aria-label="글씨 색" value={s.textColor ?? effectiveText(s)} onChange={event => patchSelected({ textColor: event.target.value })} className="absolute inset-0 opacity-0 cursor-pointer" /></label>
        <div className={`pointer-events-none flex items-center gap-0.5 px-1 rounded-lg border ${isDarkMode ? 'border-slate-700 bg-slate-950/60' : 'border-slate-200 bg-slate-50'}`}><span className="px-1 text-[10px] font-medium opacity-60">크기</span><button type="button" title="글씨 작게" aria-label="글씨 작게" onClick={() => patchSelected({ fontSize: Math.max(8, size - 2) })} className={`pointer-events-auto w-7 h-7 rounded-md flex items-center justify-center ${btn}`}><Minus className="w-3.5 h-3.5" /></button><span className="pointer-events-none w-8 text-center text-xs font-semibold tabular-nums">{size}</span><button type="button" title="글씨 크게" aria-label="글씨 크게" onClick={() => patchSelected({ fontSize: Math.min(96, size + 2) })} className={`pointer-events-auto w-7 h-7 rounded-md flex items-center justify-center ${btn}`}><Plus className="w-3.5 h-3.5" /></button></div>
        <label className={`pointer-events-auto relative flex items-center h-8 rounded-lg border ${isDarkMode ? 'bg-slate-950 border-slate-700' : 'bg-white border-slate-200'}`}><select title="글꼴" aria-label="글꼴" value={s.fontFamily ?? 'sans'} onChange={event => { const value = canvasFontFromValue(event.target.value); patchSelected(value === 'custom' ? { fontFamily: 'custom', customFontFamily: s.customFontFamily } : { fontFamily: value, customFontFamily: undefined }); }} className={`h-full min-w-20 appearance-none bg-transparent rounded-lg text-xs font-medium pl-2 pr-7 outline-none ${isDarkMode ? 'text-slate-200' : 'text-slate-700'}`}>{CANVAS_FONT_KEYS.map(key => <option key={key} value={key} className={isDarkMode ? 'bg-slate-900 text-slate-200' : 'bg-white text-slate-800'}>{CANVAS_FONTS[key].label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-1.5 w-3.5 h-3.5 opacity-60" /></label>
        {s.fontFamily === 'custom' && <><input type="text" list={`canvas-font-families-${s.id}`} title="폰트 직접입력" aria-label="폰트 직접입력" defaultValue={s.customFontFamily ?? ''} onBlur={event => applyCustomFontFamily(event.target.value)} onChange={event => event.currentTarget.value && applyCustomFontFamily(event.currentTarget.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); applyCustomFontFamily(event.currentTarget.value); } }} onDoubleClick={event => event.stopPropagation()} onPointerDown={event => event.stopPropagation()} placeholder="Noto Sans KR" className={`pointer-events-auto h-8 w-44 rounded-lg border px-2 text-xs ${isDarkMode ? 'bg-slate-950 border-slate-700' : 'bg-white border-slate-200'}`} /><datalist id={`canvas-font-families-${s.id}`}>{installedFontFamilies.map(font => <option key={font} value={font} />)}</datalist></>}
      </div>
      <div className={`flex flex-wrap items-center gap-2 pt-1.5 border-t pointer-events-none ${isDarkMode ? 'border-slate-700' : 'border-slate-100'}`}><span className="pointer-events-none px-1 text-[10px] font-semibold tracking-wide opacity-60">문단</span><div className={`pointer-events-none flex items-center gap-0.5 p-0.5 rounded-lg ${isDarkMode ? 'bg-slate-950/70' : 'bg-slate-50'}`}>{([['left', AlignLeft, '왼쪽 정렬'], ['center', AlignCenter, '가운데 정렬'], ['right', AlignRight, '오른쪽 정렬']] as const).map(([alignment, Icon, label]) => <button key={alignment} type="button" aria-label={label} title={label} onClick={() => patchSelected({ textAlign: alignment })} className={`pointer-events-auto w-8 h-8 rounded-md flex items-center justify-center ${textAlignForShape(s) === alignment ? 'bg-blue-600 text-white shadow-sm' : btn}`}><Icon className="w-4 h-4" /></button>)}</div>{editing && <><span className="pointer-events-none px-1 text-[10px] font-semibold tracking-wide opacity-60">목록</span><div className={`pointer-events-none flex items-center gap-0.5 p-0.5 rounded-lg ${isDarkMode ? 'bg-slate-950/70' : 'bg-slate-50'}`}>{([['bullet', List, '글머리표 목록'], ['dash', null, '대시 목록'], ['number', ListOrdered, '번호 목록']] as const).map(([kind, Icon, label]) => <button key={kind} type="button" onClick={() => applyList(kind)} aria-label={label} title={label} className={`pointer-events-auto w-8 h-8 rounded-md flex items-center justify-center ${btn}`}>{Icon ? <Icon className="w-4 h-4" /> : <span className="text-base leading-none">–</span>}</button>)}</div><div className={`pointer-events-none flex items-center gap-0.5 p-0.5 rounded-lg ${isDarkMode ? 'bg-slate-950/70' : 'bg-slate-50'}`}>{([{ cmd: 'bold' as const, Icon: Bold, label: '굵게' }, { cmd: 'italic' as const, Icon: Italic, label: '기울임' }, { cmd: 'underline' as const, Icon: Underline, label: '밑줄' }]).map(({ cmd, Icon, label }) => <button key={cmd} type="button" onClick={() => applyFormat(cmd)} aria-label={label} title={label} className={`pointer-events-auto w-8 h-8 rounded-md flex items-center justify-center ${btn}`}><Icon className="w-4 h-4" /></button>)}</div></>}</div>
</>;
}
